"""create models

Revision ID: dcf203363eb2
Revises: fdbec10ad40c
Create Date: 2024-08-18 00:53:52.662992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcf203363eb2"
down_revision: Union[str, None] = "fdbec10ad40c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
