"""create models

Revision ID: 7009d2396435
Revises: fd37474f6d52
Create Date: 2024-08-15 22:32:55.120889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7009d2396435"
down_revision: Union[str, None] = "fd37474f6d52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("views", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("is_buy", sa.Boolean(), nullable=True))
    op.add_column("products", sa.Column("lat", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("long", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "long")
    op.drop_column("products", "lat")
    op.drop_column("products", "is_buy")
    op.drop_column("products", "views")
    # ### end Alembic commands ###
