"""create models

Revision ID: 1e0d7fc57f56
Revises: 536c5679f74c
Create Date: 2024-08-18 11:15:42.208733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e0d7fc57f56"
down_revision: Union[str, None] = "536c5679f74c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("profile_uuid", sa.String(length=36), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_products_profile_uuid_profiles"),
        "products",
        "profiles",
        ["profile_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_profile_uuid_profiles"),
        "products",
        type_="foreignkey",
    )
    op.drop_column("products", "profile_uuid")
    # ### end Alembic commands ###
