"""create models

Revision ID: 27aecd2bc555
Revises: 1e0d7fc57f56
Create Date: 2024-08-18 16:06:07.662939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27aecd2bc555"
down_revision: Union[str, None] = "1e0d7fc57f56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("state", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "state")
    # ### end Alembic commands ###
