"""create models

Revision ID: fdbec10ad40c
Revises: 7009d2396435
Create Date: 2024-08-15 22:37:20.914107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdbec10ad40c"
down_revision: Union[str, None] = "7009d2396435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("product_uuid", sa.String(length=36), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("obj_state", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_uuid"],
            ["products.uuid"],
            name=op.f("fk_product_images_product_uuid_products"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_product_images")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_images")
    # ### end Alembic commands ###
