"""create models

Revision ID: ed86c9fbf80c
Revises: 27aecd2bc555
Create Date: 2024-08-18 22:20:27.822850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed86c9fbf80c"
down_revision: Union[str, None] = "27aecd2bc555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("price", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "price")
    # ### end Alembic commands ###
