"""create models

Revision ID: fd37474f6d52
Revises: 7231b0b392bb
Create Date: 2024-08-11 17:06:21.082501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd37474f6d52"
down_revision: Union[str, None] = "7231b0b392bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("category_uuid", sa.String(length=36), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_products_category_uuid_categorys"),
        "products",
        "categorys",
        ["category_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_category_uuid_categorys"),
        "products",
        type_="foreignkey",
    )
    op.drop_column("products", "category_uuid")
    # ### end Alembic commands ###
